baseURL = "https://arow.info/posts"
languageCode = "en-us"
title = "ARoW blog"
theme = "ananke"
googleAnalytics = "UA-71777587-1"
pygmentsUseClasses = true
pygmentsCodefences = true

[params]
custom_css = ["/css/syntax.css", "/css/custom.css"]
